/*

+-----------------------------------------------------------------+
|     Created by Chirag Mehta - http://chir.ag/projects/ntc       |
|-----------------------------------------------------------------|
|               ntc js (Name that Color JavaScript)               |
+-----------------------------------------------------------------+

All the functions, code, lists etc. have been written specifically
for the Name that Color JavaScript by Chirag Mehta unless otherwise
specified.

This script is released under the: Creative Commons License:
Attribution 2.5 http://creativecommons.org/licenses/by/2.5/

Sample Usage:

  <script type="text/javascript" src="ntc.js"></script>

  <script type="text/javascript">

    var n_match  = ntc.name("#6195ED");
    n_rgb        = n_match[0]; // This is the RGB value of the closest matching color
    n_name       = n_match[1]; // This is the text string for the name of the match
    n_exactmatch = n_match[2]; // True if exact color match, False if close-match

    alert(n_match);

  </script>

*/

var ntc = {
  init: function () {
    var color, rgb, hsl;
    for (var i = 0; i < ntc.names.length; i++) {
      color = "#" + ntc.names[i][0];
      rgb = ntc.rgb(color);
      hsl = ntc.hsl(color);
      ntc.names[i].push(rgb[0], rgb[1], rgb[2], hsl[0], hsl[1], hsl[2]);
    }
  },

  name: function (color) {
    color = color.toUpperCase();
    if (color.length < 3 || color.length > 7)
      return ["#000000", "Invalid Color: " + color, false];
    if (color.length % 3 == 0) color = "#" + color;
    if (color.length == 4)
      color =
        "#" +
        color.substr(1, 1) +
        color.substr(1, 1) +
        color.substr(2, 1) +
        color.substr(2, 1) +
        color.substr(3, 1) +
        color.substr(3, 1);

    var rgb = ntc.rgb(color);
    var r = rgb[0],
      g = rgb[1],
      b = rgb[2];
    var hsl = ntc.hsl(color);
    var h = hsl[0],
      s = hsl[1],
      l = hsl[2];
    var ndf1 = 0;
    var ndf2 = 0;
    var ndf = 0;
    var cl = -1,
      df = -1;

    for (var i = 0; i < ntc.names.length; i++) {
      if (color == "#" + ntc.names[i][0])
        return ["#" + ntc.names[i][0], ntc.names[i][1], true];

      ndf1 =
        Math.pow(r - ntc.names[i][2], 2) +
        Math.pow(g - ntc.names[i][3], 2) +
        Math.pow(b - ntc.names[i][4], 2);
      ndf2 =
        Math.pow(h - ntc.names[i][5], 2) +
        Math.pow(s - ntc.names[i][6], 2) +
        Math.pow(l - ntc.names[i][7], 2);
      ndf = ndf1 + ndf2 * 2;
      if (df < 0 || df > ndf) {
        df = ndf;
        cl = i;
      }
    }

    return cl < 0
      ? ["#000000", "Invalid Color: " + color, false]
      : ["#" + ntc.names[cl][0], ntc.names[cl][1], false];
  },

  // adopted from: Farbtastic 1.2
  // http://acko.net/dev/farbtastic
  hsl: function (color) {
    var rgb = [
      parseInt("0x" + color.substring(1, 3)) / 255,
      parseInt("0x" + color.substring(3, 5)) / 255,
      parseInt("0x" + color.substring(5, 7)) / 255,
    ];
    var min, max, delta, h, s, l;
    var r = rgb[0],
      g = rgb[1],
      b = rgb[2];

    min = Math.min(r, Math.min(g, b));
    max = Math.max(r, Math.max(g, b));
    delta = max - min;
    l = (min + max) / 2;

    s = 0;
    if (l > 0 && l < 1) s = delta / (l < 0.5 ? 2 * l : 2 - 2 * l);

    h = 0;
    if (delta > 0) {
      if (max == r && max != g) h += (g - b) / delta;
      if (max == g && max != b) h += 2 + (b - r) / delta;
      if (max == b && max != r) h += 4 + (r - g) / delta;
      h /= 6;
    }
    return [parseInt(h * 255), parseInt(s * 255), parseInt(l * 255)];
  },

  // adopted from: Farbtastic 1.2
  // http://acko.net/dev/farbtastic
  rgb: function (color) {
    return [
      parseInt("0x" + color.substring(1, 3)),
      parseInt("0x" + color.substring(3, 5)),
      parseInt("0x" + color.substring(5, 7)),
    ];
  },

  names: [
    ["000000", "Black", "Black"],
    ["000080", "Navy Blue", "Navy Blue"],
    ["0000C8", "Dark Blue", "Dark Blue"],
    ["0000FF", "Blue", "Blue"],
    ["000741", "Stratos", "Stratos"],
    ["001B1C", "Swamp", "Swamp"],
    ["002387", "Resolution Blue", "Resolution Blue"],
    ["002900", "Deep Fir", "Deep Fir"],
    ["002E20", "Burnham", "Burnham"],
    ["002FA7", "International Klein Blue", "International Klein Blue"],
    ["003153", "Prussian Blue", "Prussian Blue"],
    ["003366", "Midnight Blue", "Midnight Blue"],
    ["003399", "Smalt", "Smalt"],
    ["003532", "Deep Teal", "Deep Teal"],
    ["003E40", "Cyprus", "Cyprus"],
    ["004620", "Kaitoke Green", "Kaitoke Green"],
    ["0047AB", "Cobalt", "Cobalt"],
    ["004816", "Crusoe", "Crusoe"],
    ["004950", "Sherpa Blue", "Sherpa Blue"],
    ["0056A7", "Endeavour", "Endeavour"],
    ["00581A", "Camarone", "Camarone"],
    ["0066CC", "Science Blue", "Science Blue"],
    ["0066FF", "Blue Ribbon", "Blue Ribbon"],
    ["00755E", "Tropical Rain Forest", "Tropical Rain Forest"],
    ["0076A3", "Allports", "Allports"],
    ["007BA7", "Deep Cerulean", "Deep Cerulean"],
    ["007EC7", "Lochmara", "Lochmara"],
    ["007FFF", "Azure Radiance", "Azure Radiance"],
    ["008080", "Teal", "Teal"],
    ["0095B6", "Bondi Blue", "Bondi Blue"],
    ["009DC4", "Pacific Blue", "Pacific Blue"],
    ["00A693", "Persian Green", "Persian Green"],
    ["00A86B", "Jade", "Jade"],
    ["00CC99", "Caribbean Green", "Caribbean Green"],
    ["00CCCC", "Robin's Egg Blue", "Robin's Egg Blue"],
    ["00FF00", "Green", "Green"],
    ["00FF7F", "Spring Green", "Spring Green"],
    ["00FFFF", "Cyan / Aqua", "Cyan / Aqua"],
    ["010D1A", "Blue Charcoal", "Blue Charcoal"],
    ["011635", "Midnight", "Midnight"],
    ["011D13", "Holly", "Holly"],
    ["012731", "Daintree", "Daintree"],
    ["01361C", "Cardin Green", "Cardin Green"],
    ["01371A", "County Green", "County Green"],
    ["013E62", "Astronaut Blue", "Astronaut Blue"],
    ["013F6A", "Regal Blue", "Regal Blue"],
    ["014B43", "Aqua Deep", "Aqua Deep"],
    ["015E85", "Orient", "Orient"],
    ["016162", "Blue Stone", "Blue Stone"],
    ["016D39", "Fun Green", "Fun Green"],
    ["01796F", "Pine Green", "Pine Green"],
    ["017987", "Blue Lagoon", "Blue Lagoon"],
    ["01826B", "Deep Sea", "Deep Sea"],
    ["01A368", "Green Haze", "Green Haze"],
    ["022D15", "English Holly", "English Holly"],
    ["02402C", "Sherwood Green", "Sherwood Green"],
    ["02478E", "Congress Blue", "Congress Blue"],
    ["024E46", "Evening Sea", "Evening Sea"],
    ["026395", "Bahama Blue", "Bahama Blue"],
    ["02866F", "Observatory", "Observatory"],
    ["02A4D3", "Cerulean", "Cerulean"],
    ["03163C", "Tangaroa", "Tangaroa"],
    ["032B52", "Green Vogue", "Green Vogue"],
    ["036A6E", "Mosque", "Mosque"],
    ["041004", "Midnight Moss", "Midnight Moss"],
    ["041322", "Black Pearl", "Black Pearl"],
    ["042E4C", "Blue Whale", "Blue Whale"],
    ["044022", "Zuccini", "Zuccini"],
    ["044259", "Teal Blue", "Teal Blue"],
    ["051040", "Deep Cove", "Deep Cove"],
    ["051657", "Gulf Blue", "Gulf Blue"],
    ["055989", "Venice Blue", "Venice Blue"],
    ["056F57", "Watercourse", "Watercourse"],
    ["062A78", "Catalina Blue", "Catalina Blue"],
    ["063537", "Tiber", "Tiber"],
    ["069B81", "Gossamer", "Gossamer"],
    ["06A189", "Niagara", "Niagara"],
    ["073A50", "Tarawera", "Tarawera"],
    ["080110", "Jaguar", "Jaguar"],
    ["081910", "Black Bean", "Black Bean"],
    ["082567", "Deep Sapphire", "Deep Sapphire"],
    ["088370", "Elf Green", "Elf Green"],
    ["08E8DE", "Bright Turquoise", "Bright Turquoise"],
    ["092256", "Downriver", "Downriver"],
    ["09230F", "Palm Green", "Palm Green"],
    ["09255D", "Madison", "Madison"],
    ["093624", "Bottle Green", "Bottle Green"],
    ["095859", "Deep Sea Green", "Deep Sea Green"],
    ["097F4B", "Salem", "Salem"],
    ["0A001C", "Black Russian", "Black Russian"],
    ["0A480D", "Dark Fern", "Dark Fern"],
    ["0A6906", "Japanese Laurel", "Japanese Laurel"],
    ["0A6F75", "Atoll", "Atoll"],
    ["0B0B0B", "Cod Gray", "Cod Gray"],
    ["0B0F08", "Marshland", "Marshland"],
    ["0B1107", "Gordons Green", "Gordons Green"],
    ["0B1304", "Black Forest", "Black Forest"],
    ["0B6207", "San Felix", "San Felix"],
    ["0BDA51", "Malachite", "Malachite"],
    ["0C0B1D", "Ebony", "Ebony"],
    ["0C0D0F", "Woodsmoke", "Woodsmoke"],
    ["0C1911", "Racing Green", "Racing Green"],
    ["0C7A79", "Surfie Green", "Surfie Green"],
    ["0C8990", "Blue Chill", "Blue Chill"],
    ["0D0332", "Black Rock", "Black Rock"],
    ["0D1117", "Bunker", "Bunker"],
    ["0D1C19", "Aztec", "Aztec"],
    ["0D2E1C", "Bush", "Bush"],
    ["0E0E18", "Cinder", "Cinder"],
    ["0E2A30", "Firefly", "Firefly"],
    ["0F2D9E", "Torea Bay", "Torea Bay"],
    ["10121D", "Vulcan", "Vulcan"],
    ["101405", "Green Waterloo", "Green Waterloo"],
    ["105852", "Eden", "Eden"],
    ["110C6C", "Arapawa", "Arapawa"],
    ["120A8F", "Ultramarine", "Ultramarine"],
    ["123447", "Elephant", "Elephant"],
    ["126B40", "Jewel", "Jewel"],
    ["130000", "Diesel", "Diesel"],
    ["130A06", "Asphalt", "Asphalt"],
    ["13264D", "Blue Zodiac", "Blue Zodiac"],
    ["134F19", "Parsley", "Parsley"],
    ["140600", "Nero", "Nero"],
    ["1450AA", "Tory Blue", "Tory Blue"],
    ["151F4C", "Bunting", "Bunting"],
    ["1560BD", "Denim", "Denim"],
    ["15736B", "Genoa", "Genoa"],
    ["161928", "Mirage", "Mirage"],
    ["161D10", "Hunter Green", "Hunter Green"],
    ["162A40", "Big Stone", "Big Stone"],
    ["163222", "Celtic", "Celtic"],
    ["16322C", "Timber Green", "Timber Green"],
    ["163531", "Gable Green", "Gable Green"],
    ["171F04", "Pine Tree", "Pine Tree"],
    ["175579", "Chathams Blue", "Chathams Blue"],
    ["182D09", "Deep Forest Green", "Deep Forest Green"],
    ["18587A", "Blumine", "Blumine"],
    ["19330E", "Palm Leaf", "Palm Leaf"],
    ["193751", "Nile Blue", "Nile Blue"],
    ["1959A8", "Fun Blue", "Fun Blue"],
    ["1A1A68", "Lucky Point", "Lucky Point"],
    ["1AB385", "Mountain Meadow", "Mountain Meadow"],
    ["1B0245", "Tolopea", "Tolopea"],
    ["1B1035", "Haiti", "Haiti"],
    ["1B127B", "Deep Koamaru", "Deep Koamaru"],
    ["1B1404", "Acadia", "Acadia"],
    ["1B2F11", "Seaweed", "Seaweed"],
    ["1B3162", "Biscay", "Biscay"],
    ["1B659D", "Matisse", "Matisse"],
    ["1C1208", "Crowshead", "Crowshead"],
    ["1C1E13", "Rangoon Green", "Rangoon Green"],
    ["1C39BB", "Persian Blue", "Persian Blue"],
    ["1C402E", "Everglade", "Everglade"],
    ["1C7C7D", "Elm", "Elm"],
    ["1D6142", "Green Pea", "Green Pea"],
    ["1E0F04", "Creole", "Creole"],
    ["1E1609", "Karaka", "Karaka"],
    ["1E1708", "El Paso", "El Paso"],
    ["1E385B", "Cello", "Cello"],
    ["1E433C", "Te Papa Green", "Te Papa Green"],
    ["1E90FF", "Dodger Blue", "Dodger Blue"],
    ["1E9AB0", "Eastern Blue", "Eastern Blue"],
    ["1F120F", "Night Rider", "Night Rider"],
    ["1FC2C2", "Java", "Java"],
    ["20208D", "Jacksons Purple", "Jacksons Purple"],
    ["202E54", "Cloud Burst", "Cloud Burst"],
    ["204852", "Blue Dianne", "Blue Dianne"],
    ["211A0E", "Eternity", "Eternity"],
    ["220878", "Deep Blue", "Deep Blue"],
    ["228B22", "Forest Green", "Forest Green"],
    ["233418", "Mallard", "Mallard"],
    ["240A40", "Violet", "Violet"],
    ["240C02", "Kilamanjaro", "Kilamanjaro"],
    ["242A1D", "Log Cabin", "Log Cabin"],
    ["242E16", "Black Olive", "Black Olive"],
    ["24500F", "Green House", "Green House"],
    ["251607", "Graphite", "Graphite"],
    ["251706", "Cannon Black", "Cannon Black"],
    ["251F4F", "Port Gore", "Port Gore"],
    ["25272C", "Shark", "Shark"],
    ["25311C", "Green Kelp", "Green Kelp"],
    ["2596D1", "Curious Blue", "Curious Blue"],
    ["260368", "Paua", "Paua"],
    ["26056A", "Paris M", "Paris M"],
    ["261105", "Wood Bark", "Wood Bark"],
    ["261414", "Gondola", "Gondola"],
    ["262335", "Steel Gray", "Steel Gray"],
    ["26283B", "Ebony Clay", "Ebony Clay"],
    ["273A81", "Bay of Many", "Bay of Many"],
    ["27504B", "Plantation", "Plantation"],
    ["278A5B", "Eucalyptus", "Eucalyptus"],
    ["281E15", "Oil", "Oil"],
    ["283A77", "Astronaut", "Astronaut"],
    ["286ACD", "Mariner", "Mariner"],
    ["290C5E", "Violent Violet", "Violent Violet"],
    ["292130", "Bastille", "Bastille"],
    ["292319", "Zeus", "Zeus"],
    ["292937", "Charade", "Charade"],
    ["297B9A", "Jelly Bean", "Jelly Bean"],
    ["29AB87", "Jungle Green", "Jungle Green"],
    ["2A0359", "Cherry Pie", "Cherry Pie"],
    ["2A140E", "Coffee Bean", "Coffee Bean"],
    ["2A2630", "Baltic Sea", "Baltic Sea"],
    ["2A380B", "Turtle Green", "Turtle Green"],
    ["2A52BE", "Cerulean Blue", "Cerulean Blue"],
    ["2B0202", "Sepia Black", "Sepia Black"],
    ["2B194F", "Valhalla", "Valhalla"],
    ["2B3228", "Heavy Metal", "Heavy Metal"],
    ["2C0E8C", "Blue Gem", "Blue Gem"],
    ["2C1632", "Revolver", "Revolver"],
    ["2C2133", "Bleached Cedar", "Bleached Cedar"],
    ["2C8C84", "Lochinvar", "Lochinvar"],
    ["2D2510", "Mikado", "Mikado"],
    ["2D383A", "Outer Space", "Outer Space"],
    ["2D569B", "St Tropaz", "St Tropaz"],
    ["2E0329", "Jacaranda", "Jacaranda"],
    ["2E1905", "Jacko Bean", "Jacko Bean"],
    ["2E3222", "Rangitoto", "Rangitoto"],
    ["2E3F62", "Rhino", "Rhino"],
    ["2E8B57", "Sea Green", "Sea Green"],
    ["2EBFD4", "Scooter", "Scooter"],
    ["2F270E", "Onion", "Onion"],
    ["2F3CB3", "Governor Bay", "Governor Bay"],
    ["2F519E", "Sapphire", "Sapphire"],
    ["2F5A57", "Spectra", "Spectra"],
    ["2F6168", "Casal", "Casal"],
    ["300529", "Melanzane", "Melanzane"],
    ["301F1E", "Cocoa Brown", "Cocoa Brown"],
    ["302A0F", "Woodrush", "Woodrush"],
    ["304B6A", "San Juan", "San Juan"],
    ["30D5C8", "Turquoise", "Turquoise"],
    ["311C17", "Eclipse", "Eclipse"],
    ["314459", "Pickled Bluewood", "Pickled Bluewood"],
    ["315BA1", "Azure", "Azure"],
    ["31728D", "Calypso", "Calypso"],
    ["317D82", "Paradiso", "Paradiso"],
    ["32127A", "Persian Indigo", "Persian Indigo"],
    ["32293A", "Blackcurrant", "Blackcurrant"],
    ["323232", "Mine Shaft", "Mine Shaft"],
    ["325D52", "Stromboli", "Stromboli"],
    ["327C14", "Bilbao", "Bilbao"],
    ["327DA0", "Astral", "Astral"],
    ["33036B", "Christalle", "Christalle"],
    ["33292F", "Thunder", "Thunder"],
    ["33CC99", "Shamrock", "Shamrock"],
    ["341515", "Tamarind", "Tamarind"],
    ["350036", "Mardi Gras", "Mardi Gras"],
    ["350E42", "Valentino", "Valentino"],
    ["350E57", "Jagger", "Jagger"],
    ["353542", "Tuna", "Tuna"],
    ["354E8C", "Chambray", "Chambray"],
    ["363050", "Martinique", "Martinique"],
    ["363534", "Tuatara", "Tuatara"],
    ["363C0D", "Waiouru", "Waiouru"],
    ["36747D", "Ming", "Ming"],
    ["368716", "La Palma", "La Palma"],
    ["370202", "Chocolate", "Chocolate"],
    ["371D09", "Clinker", "Clinker"],
    ["37290E", "Brown Tumbleweed", "Brown Tumbleweed"],
    ["373021", "Birch", "Birch"],
    ["377475", "Oracle", "Oracle"],
    ["380474", "Blue Diamond", "Blue Diamond"],
    ["381A51", "Grape", "Grape"],
    ["383533", "Dune", "Dune"],
    ["384555", "Oxford Blue", "Oxford Blue"],
    ["384910", "Clover", "Clover"],
    ["394851", "Limed Spruce", "Limed Spruce"],
    ["396413", "Dell", "Dell"],
    ["3A0020", "Toledo", "Toledo"],
    ["3A2010", "Sambuca", "Sambuca"],
    ["3A2A6A", "Jacarta", "Jacarta"],
    ["3A686C", "William", "William"],
    ["3A6A47", "Killarney", "Killarney"],
    ["3AB09E", "Keppel", "Keppel"],
    ["3B000B", "Temptress", "Temptress"],
    ["3B0910", "Aubergine", "Aubergine"],
    ["3B1F1F", "Jon", "Jon"],
    ["3B2820", "Treehouse", "Treehouse"],
    ["3B7A57", "Amazon", "Amazon"],
    ["3B91B4", "Boston Blue", "Boston Blue"],
    ["3C0878", "Windsor", "Windsor"],
    ["3C1206", "Rebel", "Rebel"],
    ["3C1F76", "Meteorite", "Meteorite"],
    ["3C2005", "Dark Ebony", "Dark Ebony"],
    ["3C3910", "Camouflage", "Camouflage"],
    ["3C4151", "Bright Gray", "Bright Gray"],
    ["3C4443", "Cape Cod", "Cape Cod"],
    ["3C493A", "Lunar Green", "Lunar Green"],
    ["3D0C02", "Bean  ", "Bean  "],
    ["3D2B1F", "Bistre", "Bistre"],
    ["3D7D52", "Goblin", "Goblin"],
    ["3E0480", "Kingfisher Daisy", "Kingfisher Daisy"],
    ["3E1C14", "Cedar", "Cedar"],
    ["3E2B23", "English Walnut", "English Walnut"],
    ["3E2C1C", "Black Marlin", "Black Marlin"],
    ["3E3A44", "Ship Gray", "Ship Gray"],
    ["3EABBF", "Pelorous", "Pelorous"],
    ["3F2109", "Bronze", "Bronze"],
    ["3F2500", "Cola", "Cola"],
    ["3F3002", "Madras", "Madras"],
    ["3F307F", "Minsk", "Minsk"],
    ["3F4C3A", "Cabbage Pont", "Cabbage Pont"],
    ["3F583B", "Tom Thumb", "Tom Thumb"],
    ["3F5D53", "Mineral Green", "Mineral Green"],
    ["3FC1AA", "Puerto Rico", "Puerto Rico"],
    ["3FFF00", "Harlequin", "Harlequin"],
    ["401801", "Brown Pod", "Brown Pod"],
    ["40291D", "Cork", "Cork"],
    ["403B38", "Masala", "Masala"],
    ["403D19", "Thatch Green", "Thatch Green"],
    ["405169", "Fiord", "Fiord"],
    ["40826D", "Viridian", "Viridian"],
    ["40A860", "Chateau Green", "Chateau Green"],
    ["410056", "Ripe Plum", "Ripe Plum"],
    ["411F10", "Paco", "Paco"],
    ["412010", "Deep Oak", "Deep Oak"],
    ["413C37", "Merlin", "Merlin"],
    ["414257", "Gun Powder", "Gun Powder"],
    ["414C7D", "East Bay", "East Bay"],
    ["4169E1", "Royal Blue", "Royal Blue"],
    ["41AA78", "Ocean Green", "Ocean Green"],
    ["420303", "Burnt Maroon", "Burnt Maroon"],
    ["423921", "Lisbon Brown", "Lisbon Brown"],
    ["427977", "Faded Jade", "Faded Jade"],
    ["431560", "Scarlet Gum", "Scarlet Gum"],
    ["433120", "Iroko", "Iroko"],
    ["433E37", "Armadillo", "Armadillo"],
    ["434C59", "River Bed", "River Bed"],
    ["436A0D", "Green Leaf", "Green Leaf"],
    ["44012D", "Barossa", "Barossa"],
    ["441D00", "Morocco Brown", "Morocco Brown"],
    ["444954", "Mako", "Mako"],
    ["454936", "Kelp", "Kelp"],
    ["456CAC", "San Marino", "San Marino"],
    ["45B1E8", "Picton Blue", "Picton Blue"],
    ["460B41", "Loulou", "Loulou"],
    ["462425", "Crater Brown", "Crater Brown"],
    ["465945", "Gray Asparagus", "Gray Asparagus"],
    ["4682B4", "Steel Blue", "Steel Blue"],
    ["480404", "Rustic Red", "Rustic Red"],
    ["480607", "Bulgarian Rose", "Bulgarian Rose"],
    ["480656", "Clairvoyant", "Clairvoyant"],
    ["481C1C", "Cocoa Bean", "Cocoa Bean"],
    ["483131", "Woody Brown", "Woody Brown"],
    ["483C32", "Taupe", "Taupe"],
    ["49170C", "Van Cleef", "Van Cleef"],
    ["492615", "Brown Derby", "Brown Derby"],
    ["49371B", "Metallic Bronze", "Metallic Bronze"],
    ["495400", "Verdun Green", "Verdun Green"],
    ["496679", "Blue Bayoux", "Blue Bayoux"],
    ["497183", "Bismark", "Bismark"],
    ["4A2A04", "Bracken", "Bracken"],
    ["4A3004", "Deep Bronze", "Deep Bronze"],
    ["4A3C30", "Mondo", "Mondo"],
    ["4A4244", "Tundora", "Tundora"],
    ["4A444B", "Gravel", "Gravel"],
    ["4A4E5A", "Trout", "Trout"],
    ["4B0082", "Pigment Indigo", "Pigment Indigo"],
    ["4B5D52", "Nandor", "Nandor"],
    ["4C3024", "Saddle", "Saddle"],
    ["4C4F56", "Abbey", "Abbey"],
    ["4D0135", "Blackberry", "Blackberry"],
    ["4D0A18", "Cab Sav", "Cab Sav"],
    ["4D1E01", "Indian Tan", "Indian Tan"],
    ["4D282D", "Cowboy", "Cowboy"],
    ["4D282E", "Livid Brown", "Livid Brown"],
    ["4D3833", "Rock", "Rock"],
    ["4D3D14", "Punga", "Punga"],
    ["4D400F", "Bronzetone", "Bronzetone"],
    ["4D5328", "Woodland", "Woodland"],
    ["4E0606", "Mahogany", "Mahogany"],
    ["4E2A5A", "Bossanova", "Bossanova"],
    ["4E3B41", "Matterhorn", "Matterhorn"],
    ["4E420C", "Bronze Olive", "Bronze Olive"],
    ["4E4562", "Mulled Wine", "Mulled Wine"],
    ["4E6649", "Axolotl", "Axolotl"],
    ["4E7F9E", "Wedgewood", "Wedgewood"],
    ["4EABD1", "Shakespeare", "Shakespeare"],
    ["4F1C70", "Honey Flower", "Honey Flower"],
    ["4F2398", "Daisy Bush", "Daisy Bush"],
    ["4F69C6", "Indigo", "Indigo"],
    ["4F7942", "Fern Green", "Fern Green"],
    ["4F9D5D", "Fruit Salad", "Fruit Salad"],
    ["4FA83D", "Apple", "Apple"],
    ["504351", "Mortar", "Mortar"],
    ["507096", "Kashmir Blue", "Kashmir Blue"],
    ["507672", "Cutty Sark", "Cutty Sark"],
    ["50C878", "Emerald", "Emerald"],
    ["514649", "Emperor", "Emperor"],
    ["516E3D", "Chalet Green", "Chalet Green"],
    ["517C66", "Como", "Como"],
    ["51808F", "Smalt Blue", "Smalt Blue"],
    ["52001F", "Castro", "Castro"],
    ["520C17", "Maroon Oak", "Maroon Oak"],
    ["523C94", "Gigas", "Gigas"],
    ["533455", "Voodoo", "Voodoo"],
    ["534491", "Victoria", "Victoria"],
    ["53824B", "Hippie Green", "Hippie Green"],
    ["541012", "Heath", "Heath"],
    ["544333", "Judge Gray", "Judge Gray"],
    ["54534D", "Fuscous Gray", "Fuscous Gray"],
    ["549019", "Vida Loca", "Vida Loca"],
    ["55280C", "Cioccolato", "Cioccolato"],
    ["555B10", "Saratoga", "Saratoga"],
    ["556D56", "Finlandia", "Finlandia"],
    ["5590D9", "Havelock Blue", "Havelock Blue"],
    ["56B4BE", "Fountain Blue", "Fountain Blue"],
    ["578363", "Spring Leaves", "Spring Leaves"],
    ["583401", "Saddle Brown", "Saddle Brown"],
    ["585562", "Scarpa Flow", "Scarpa Flow"],
    ["587156", "Cactus", "Cactus"],
    ["589AAF", "Hippie Blue", "Hippie Blue"],
    ["591D35", "Wine Berry", "Wine Berry"],
    ["592804", "Brown Bramble", "Brown Bramble"],
    ["593737", "Congo Brown", "Congo Brown"],
    ["594433", "Millbrook", "Millbrook"],
    ["5A6E9C", "Waikawa Gray", "Waikawa Gray"],
    ["5A87A0", "Horizon", "Horizon"],
    ["5B3013", "Jambalaya", "Jambalaya"],
    ["5C0120", "Bordeaux", "Bordeaux"],
    ["5C0536", "Mulberry Wood", "Mulberry Wood"],
    ["5C2E01", "Carnaby Tan", "Carnaby Tan"],
    ["5C5D75", "Comet", "Comet"],
    ["5D1E0F", "Redwood", "Redwood"],
    ["5D4C51", "Don Juan", "Don Juan"],
    ["5D5C58", "Chicago", "Chicago"],
    ["5D5E37", "Verdigris", "Verdigris"],
    ["5D7747", "Dingley", "Dingley"],
    ["5DA19F", "Breaker Bay", "Breaker Bay"],
    ["5E483E", "Kabul", "Kabul"],
    ["5E5D3B", "Hemlock", "Hemlock"],
    ["5F3D26", "Irish Coffee", "Irish Coffee"],
    ["5F5F6E", "Mid Gray", "Mid Gray"],
    ["5F6672", "Shuttle Gray", "Shuttle Gray"],
    ["5FA777", "Aqua Forest", "Aqua Forest"],
    ["5FB3AC", "Tradewind", "Tradewind"],
    ["604913", "Horses Neck", "Horses Neck"],
    ["605B73", "Smoky", "Smoky"],
    ["606E68", "Corduroy", "Corduroy"],
    ["6093D1", "Danube", "Danube"],
    ["612718", "Espresso", "Espresso"],
    ["614051", "Eggplant", "Eggplant"],
    ["615D30", "Costa Del Sol", "Costa Del Sol"],
    ["61845F", "Glade Green", "Glade Green"],
    ["622F30", "Buccaneer", "Buccaneer"],
    ["623F2D", "Quincy", "Quincy"],
    ["624E9A", "Butterfly Bush", "Butterfly Bush"],
    ["625119", "West Coast", "West Coast"],
    ["626649", "Finch", "Finch"],
    ["639A8F", "Patina", "Patina"],
    ["63B76C", "Fern", "Fern"],
    ["6456B7", "Blue Violet", "Blue Violet"],
    ["646077", "Dolphin", "Dolphin"],
    ["646463", "Storm Dust", "Storm Dust"],
    ["646A54", "Siam", "Siam"],
    ["646E75", "Nevada", "Nevada"],
    ["6495ED", "Cornflower Blue", "Cornflower Blue"],
    ["64CCDB", "Viking", "Viking"],
    ["65000B", "Rosewood", "Rosewood"],
    ["651A14", "Cherrywood", "Cherrywood"],
    ["652DC1", "Purple Heart", "Purple Heart"],
    ["657220", "Fern Frond", "Fern Frond"],
    ["65745D", "Willow Grove", "Willow Grove"],
    ["65869F", "Hoki", "Hoki"],
    ["660045", "Pompadour", "Pompadour"],
    ["660099", "Purple", "Purple"],
    ["66023C", "Tyrian Purple", "Tyrian Purple"],
    ["661010", "Dark Tan", "Dark Tan"],
    ["66B58F", "Silver Tree", "Silver Tree"],
    ["66FF00", "Bright Green", "Bright Green"],
    ["66FF66", "Screamin' Green", "Screamin' Green"],
    ["67032D", "Black Rose", "Black Rose"],
    ["675FA6", "Scampi", "Scampi"],
    ["676662", "Ironside Gray", "Ironside Gray"],
    ["678975", "Viridian Green", "Viridian Green"],
    ["67A712", "Christi", "Christi"],
    ["683600", "Nutmeg Wood Finish", "Nutmeg Wood Finish"],
    ["685558", "Zambezi", "Zambezi"],
    ["685E6E", "Salt Box", "Salt Box"],
    ["692545", "Tawny Port", "Tawny Port"],
    ["692D54", "Finn", "Finn"],
    ["695F62", "Scorpion", "Scorpion"],
    ["697E9A", "Lynch", "Lynch"],
    ["6A442E", "Spice", "Spice"],
    ["6A5D1B", "Himalaya", "Himalaya"],
    ["6A6051", "Soya Bean", "Soya Bean"],
    ["6B2A14", "Hairy Heath", "Hairy Heath"],
    ["6B3FA0", "Royal Purple", "Royal Purple"],
    ["6B4E31", "Shingle Fawn", "Shingle Fawn"],
    ["6B5755", "Dorado", "Dorado"],
    ["6B8BA2", "Bermuda Gray", "Bermuda Gray"],
    ["6B8E23", "Olive Drab", "Olive Drab"],
    ["6C3082", "Eminence", "Eminence"],
    ["6CDAE7", "Turquoise Blue", "Turquoise Blue"],
    ["6D0101", "Lonestar", "Lonestar"],
    ["6D5E54", "Pine Cone", "Pine Cone"],
    ["6D6C6C", "Dove Gray", "Dove Gray"],
    ["6D9292", "Juniper", "Juniper"],
    ["6D92A1", "Gothic", "Gothic"],
    ["6E0902", "Red Oxide", "Red Oxide"],
    ["6E1D14", "Moccaccino", "Moccaccino"],
    ["6E4826", "Pickled Bean", "Pickled Bean"],
    ["6E4B26", "Dallas", "Dallas"],
    ["6E6D57", "Kokoda", "Kokoda"],
    ["6E7783", "Pale Sky", "Pale Sky"],
    ["6F440C", "Cafe Royale", "Cafe Royale"],
    ["6F6A61", "Flint", "Flint"],
    ["6F8E63", "Highland", "Highland"],
    ["6F9D02", "Limeade", "Limeade"],
    ["6FD0C5", "Downy", "Downy"],
    ["701C1C", "Persian Plum", "Persian Plum"],
    ["704214", "Sepia", "Sepia"],
    ["704A07", "Antique Bronze", "Antique Bronze"],
    ["704F50", "Ferra", "Ferra"],
    ["706555", "Coffee", "Coffee"],
    ["708090", "Slate Gray", "Slate Gray"],
    ["711A00", "Cedar Wood Finish", "Cedar Wood Finish"],
    ["71291D", "Metallic Copper", "Metallic Copper"],
    ["714693", "Affair", "Affair"],
    ["714AB2", "Studio", "Studio"],
    ["715D47", "Tobacco Brown", "Tobacco Brown"],
    ["716338", "Yellow Metal", "Yellow Metal"],
    ["716B56", "Peat", "Peat"],
    ["716E10", "Olivetone", "Olivetone"],
    ["717486", "Storm Gray", "Storm Gray"],
    ["718080", "Sirocco", "Sirocco"],
    ["71D9E2", "Aquamarine Blue", "Aquamarine Blue"],
    ["72010F", "Venetian Red", "Venetian Red"],
    ["724A2F", "Old Copper", "Old Copper"],
    ["726D4E", "Go Ben", "Go Ben"],
    ["727B89", "Raven", "Raven"],
    ["731E8F", "Seance", "Seance"],
    ["734A12", "Raw Umber", "Raw Umber"],
    ["736C9F", "Kimberly", "Kimberly"],
    ["736D58", "Crocodile", "Crocodile"],
    ["737829", "Crete", "Crete"],
    ["738678", "Xanadu", "Xanadu"],
    ["74640D", "Spicy Mustard", "Spicy Mustard"],
    ["747D63", "Limed Ash", "Limed Ash"],
    ["747D83", "Rolling Stone", "Rolling Stone"],
    ["748881", "Blue Smoke", "Blue Smoke"],
    ["749378", "Laurel", "Laurel"],
    ["74C365", "Mantis", "Mantis"],
    ["755A57", "Russett", "Russett"],
    ["7563A8", "Deluge", "Deluge"],
    ["76395D", "Cosmic", "Cosmic"],
    ["7666C6", "Blue Marguerite", "Blue Marguerite"],
    ["76BD17", "Lima", "Lima"],
    ["76D7EA", "Sky Blue", "Sky Blue"],
    ["770F05", "Dark Burgundy", "Dark Burgundy"],
    ["771F1F", "Crown of Thorns", "Crown of Thorns"],
    ["773F1A", "Walnut", "Walnut"],
    ["776F61", "Pablo", "Pablo"],
    ["778120", "Pacifika", "Pacifika"],
    ["779E86", "Oxley", "Oxley"],
    ["77DD77", "Pastel Green", "Pastel Green"],
    ["780109", "Japanese Maple", "Japanese Maple"],
    ["782D19", "Mocha", "Mocha"],
    ["782F16", "Peanut", "Peanut"],
    ["78866B", "Camouflage Green", "Camouflage Green"],
    ["788A25", "Wasabi", "Wasabi"],
    ["788BBA", "Ship Cove", "Ship Cove"],
    ["78A39C", "Sea Nymph", "Sea Nymph"],
    ["795D4C", "Roman Coffee", "Roman Coffee"],
    ["796878", "Old Lavender", "Old Lavender"],
    ["796989", "Rum", "Rum"],
    ["796A78", "Fedora", "Fedora"],
    ["796D62", "Sandstone", "Sandstone"],
    ["79DEEC", "Spray", "Spray"],
    ["7A013A", "Siren", "Siren"],
    ["7A58C1", "Fuchsia Blue", "Fuchsia Blue"],
    ["7A7A7A", "Boulder", "Boulder"],
    ["7A89B8", "Wild Blue Yonder", "Wild Blue Yonder"],
    ["7AC488", "De York", "De York"],
    ["7B3801", "Red Beech", "Red Beech"],
    ["7B3F00", "Cinnamon", "Cinnamon"],
    ["7B6608", "Yukon Gold", "Yukon Gold"],
    ["7B7874", "Tapa", "Tapa"],
    ["7B7C94", "Waterloo ", "Waterloo "],
    ["7B8265", "Flax Smoke", "Flax Smoke"],
    ["7B9F80", "Amulet", "Amulet"],
    ["7BA05B", "Asparagus", "Asparagus"],
    ["7C1C05", "Kenyan Copper", "Kenyan Copper"],
    ["7C7631", "Pesto", "Pesto"],
    ["7C778A", "Topaz", "Topaz"],
    ["7C7B7A", "Concord", "Concord"],
    ["7C7B82", "Jumbo", "Jumbo"],
    ["7C881A", "Trendy Green", "Trendy Green"],
    ["7CA1A6", "Gumbo", "Gumbo"],
    ["7CB0A1", "Acapulco", "Acapulco"],
    ["7CB7BB", "Neptune", "Neptune"],
    ["7D2C14", "Pueblo", "Pueblo"],
    ["7DA98D", "Bay Leaf", "Bay Leaf"],
    ["7DC8F7", "Malibu", "Malibu"],
    ["7DD8C6", "Bermuda", "Bermuda"],
    ["7E3A15", "Copper Canyon", "Copper Canyon"],
    ["7F1734", "Claret", "Claret"],
    ["7F3A02", "Peru Tan", "Peru Tan"],
    ["7F626D", "Falcon", "Falcon"],
    ["7F7589", "Mobster", "Mobster"],
    ["7F76D3", "Moody Blue", "Moody Blue"],
    ["7FFF00", "Chartreuse", "Chartreuse"],
    ["7FFFD4", "Aquamarine", "Aquamarine"],
    ["800000", "Maroon", "Maroon"],
    ["800B47", "Rose Bud Cherry", "Rose Bud Cherry"],
    ["801818", "Falu Red", "Falu Red"],
    ["80341F", "Red Robin", "Red Robin"],
    ["803790", "Vivid Violet", "Vivid Violet"],
    ["80461B", "Russet", "Russet"],
    ["807E79", "Friar Gray", "Friar Gray"],
    ["808000", "Olive", "Olive"],
    ["808080", "Gray", "Gray"],
    ["80B3AE", "Gulf Stream", "Gulf Stream"],
    ["80B3C4", "Glacier", "Glacier"],
    ["80CCEA", "Seagull", "Seagull"],
    ["81422C", "Nutmeg", "Nutmeg"],
    ["816E71", "Spicy Pink", "Spicy Pink"],
    ["817377", "Empress", "Empress"],
    ["819885", "Spanish Green", "Spanish Green"],
    ["826F65", "Sand Dune", "Sand Dune"],
    ["828685", "Gunsmoke", "Gunsmoke"],
    ["828F72", "Battleship Gray", "Battleship Gray"],
    ["831923", "Merlot", "Merlot"],
    ["837050", "Shadow", "Shadow"],
    ["83AA5D", "Chelsea Cucumber", "Chelsea Cucumber"],
    ["83D0C6", "Monte Carlo", "Monte Carlo"],
    ["843179", "Plum", "Plum"],
    ["84A0A0", "Granny Smith", "Granny Smith"],
    ["8581D9", "Chetwode Blue", "Chetwode Blue"],
    ["858470", "Bandicoot", "Bandicoot"],
    ["859FAF", "Bali Hai", "Bali Hai"],
    ["85C4CC", "Half Baked", "Half Baked"],
    ["860111", "Red Devil", "Red Devil"],
    ["863C3C", "Lotus", "Lotus"],
    ["86483C", "Ironstone", "Ironstone"],
    ["864D1E", "Bull Shot", "Bull Shot"],
    ["86560A", "Rusty Nail", "Rusty Nail"],
    ["868974", "Bitter", "Bitter"],
    ["86949F", "Regent Gray", "Regent Gray"],
    ["871550", "Disco", "Disco"],
    ["87756E", "Americano", "Americano"],
    ["877C7B", "Hurricane", "Hurricane"],
    ["878D91", "Oslo Gray", "Oslo Gray"],
    ["87AB39", "Sushi", "Sushi"],
    ["885342", "Spicy Mix", "Spicy Mix"],
    ["886221", "Kumera", "Kumera"],
    ["888387", "Suva Gray", "Suva Gray"],
    ["888D65", "Avocado", "Avocado"],
    ["893456", "Camelot", "Camelot"],
    ["893843", "Solid Pink", "Solid Pink"],
    ["894367", "Cannon Pink", "Cannon Pink"],
    ["897D6D", "Makara", "Makara"],
    ["8A3324", "Burnt Umber", "Burnt Umber"],
    ["8A73D6", "True V", "True V"],
    ["8A8360", "Clay Creek", "Clay Creek"],
    ["8A8389", "Monsoon", "Monsoon"],
    ["8A8F8A", "Stack", "Stack"],
    ["8AB9F1", "Jordy Blue", "Jordy Blue"],
    ["8B00FF", "Electric Violet", "Electric Violet"],
    ["8B0723", "Monarch", "Monarch"],
    ["8B6B0B", "Corn Harvest", "Corn Harvest"],
    ["8B8470", "Olive Haze", "Olive Haze"],
    ["8B847E", "Schooner", "Schooner"],
    ["8B8680", "Natural Gray", "Natural Gray"],
    ["8B9C90", "Mantle", "Mantle"],
    ["8B9FEE", "Portage", "Portage"],
    ["8BA690", "Envy", "Envy"],
    ["8BA9A5", "Cascade", "Cascade"],
    ["8BE6D8", "Riptide", "Riptide"],
    ["8C055E", "Cardinal Pink", "Cardinal Pink"],
    ["8C472F", "Mule Fawn", "Mule Fawn"],
    ["8C5738", "Potters Clay", "Potters Clay"],
    ["8C6495", "Trendy Pink", "Trendy Pink"],
    ["8D0226", "Paprika", "Paprika"],
    ["8D3D38", "Sanguine Brown", "Sanguine Brown"],
    ["8D3F3F", "Tosca", "Tosca"],
    ["8D7662", "Cement", "Cement"],
    ["8D8974", "Granite Green", "Granite Green"],
    ["8D90A1", "Manatee", "Manatee"],
    ["8DA8CC", "Polo Blue", "Polo Blue"],
    ["8E0000", "Red Berry", "Red Berry"],
    ["8E4D1E", "Rope", "Rope"],
    ["8E6F70", "Opium", "Opium"],
    ["8E775E", "Domino", "Domino"],
    ["8E8190", "Mamba", "Mamba"],
    ["8EABC1", "Nepal", "Nepal"],
    ["8F021C", "Pohutukawa", "Pohutukawa"],
    ["8F3E33", "El Salva", "El Salva"],
    ["8F4B0E", "Korma", "Korma"],
    ["8F8176", "Squirrel", "Squirrel"],
    ["8FD6B4", "Vista Blue", "Vista Blue"],
    ["900020", "Burgundy", "Burgundy"],
    ["901E1E", "Old Brick", "Old Brick"],
    ["907874", "Hemp", "Hemp"],
    ["907B71", "Almond Frost", "Almond Frost"],
    ["908D39", "Sycamore", "Sycamore"],
    ["92000A", "Sangria", "Sangria"],
    ["924321", "Cumin", "Cumin"],
    ["926F5B", "Beaver", "Beaver"],
    ["928573", "Stonewall", "Stonewall"],
    ["928590", "Venus", "Venus"],
    ["9370DB", "Medium Purple", "Medium Purple"],
    ["93CCEA", "Cornflower", "Cornflower"],
    ["93DFB8", "Algae Green", "Algae Green"],
    ["944747", "Copper Rust", "Copper Rust"],
    ["948771", "Arrowtown", "Arrowtown"],
    ["950015", "Scarlett", "Scarlett"],
    ["956387", "Strikemaster", "Strikemaster"],
    ["959396", "Mountain Mist", "Mountain Mist"],
    ["960018", "Carmine", "Carmine"],
    ["964B00", "Brown", "Brown"],
    ["967059", "Leather", "Leather"],
    ["9678B6", "Purple Mountain's Majesty", "Purple Mountain's Majesty"],
    ["967BB6", "Lavender Purple", "Lavender Purple"],
    ["96A8A1", "Pewter", "Pewter"],
    ["96BBAB", "Summer Green", "Summer Green"],
    ["97605D", "Au Chico", "Au Chico"],
    ["9771B5", "Wisteria", "Wisteria"],
    ["97CD2D", "Atlantis", "Atlantis"],
    ["983D61", "Vin Rouge", "Vin Rouge"],
    ["9874D3", "Lilac Bush", "Lilac Bush"],
    ["98777B", "Bazaar", "Bazaar"],
    ["98811B", "Hacienda", "Hacienda"],
    ["988D77", "Pale Oyster", "Pale Oyster"],
    ["98FF98", "Mint Green", "Mint Green"],
    ["990066", "Fresh Eggplant", "Fresh Eggplant"],
    ["991199", "Violet Eggplant", "Violet Eggplant"],
    ["991613", "Tamarillo", "Tamarillo"],
    ["991B07", "Totem Pole", "Totem Pole"],
    ["996666", "Copper Rose", "Copper Rose"],
    ["9966CC", "Amethyst", "Amethyst"],
    ["997A8D", "Mountbatten Pink", "Mountbatten Pink"],
    ["9999CC", "Blue Bell", "Blue Bell"],
    ["9A3820", "Prairie Sand", "Prairie Sand"],
    ["9A6E61", "Toast", "Toast"],
    ["9A9577", "Gurkha", "Gurkha"],
    ["9AB973", "Olivine", "Olivine"],
    ["9AC2B8", "Shadow Green", "Shadow Green"],
    ["9B4703", "Oregon", "Oregon"],
    ["9B9E8F", "Lemon Grass", "Lemon Grass"],
    ["9C3336", "Stiletto", "Stiletto"],
    ["9D5616", "Hawaiian Tan", "Hawaiian Tan"],
    ["9DACB7", "Gull Gray", "Gull Gray"],
    ["9DC209", "Pistachio", "Pistachio"],
    ["9DE093", "Granny Smith Apple", "Granny Smith Apple"],
    ["9DE5FF", "Anakiwa", "Anakiwa"],
    ["9E5302", "Chelsea Gem", "Chelsea Gem"],
    ["9E5B40", "Sepia Skin", "Sepia Skin"],
    ["9EA587", "Sage", "Sage"],
    ["9EA91F", "Citron", "Citron"],
    ["9EB1CD", "Rock Blue", "Rock Blue"],
    ["9EDEE0", "Morning Glory", "Morning Glory"],
    ["9F381D", "Cognac", "Cognac"],
    ["9F821C", "Reef Gold", "Reef Gold"],
    ["9F9F9C", "Star Dust", "Star Dust"],
    ["9FA0B1", "Santas Gray", "Santas Gray"],
    ["9FD7D3", "Sinbad", "Sinbad"],
    ["9FDD8C", "Feijoa", "Feijoa"],
    ["A02712", "Tabasco", "Tabasco"],
    ["A1750D", "Buttered Rum", "Buttered Rum"],
    ["A1ADB5", "Hit Gray", "Hit Gray"],
    ["A1C50A", "Citrus", "Citrus"],
    ["A1DAD7", "Aqua Island", "Aqua Island"],
    ["A1E9DE", "Water Leaf", "Water Leaf"],
    ["A2006D", "Flirt", "Flirt"],
    ["A23B6C", "Rouge", "Rouge"],
    ["A26645", "Cape Palliser", "Cape Palliser"],
    ["A2AAB3", "Gray Chateau", "Gray Chateau"],
    ["A2AEAB", "Edward", "Edward"],
    ["A3807B", "Pharlap", "Pharlap"],
    ["A397B4", "Amethyst Smoke", "Amethyst Smoke"],
    ["A3E3ED", "Blizzard Blue", "Blizzard Blue"],
    ["A4A49D", "Delta", "Delta"],
    ["A4A6D3", "Wistful", "Wistful"],
    ["A4AF6E", "Green Smoke", "Green Smoke"],
    ["A50B5E", "Jazzberry Jam", "Jazzberry Jam"],
    ["A59B91", "Zorba", "Zorba"],
    ["A5CB0C", "Bahia", "Bahia"],
    ["A62F20", "Roof Terracotta", "Roof Terracotta"],
    ["A65529", "Paarl", "Paarl"],
    ["A68B5B", "Barley Corn", "Barley Corn"],
    ["A69279", "Donkey Brown", "Donkey Brown"],
    ["A6A29A", "Dawn", "Dawn"],
    ["A72525", "Mexican Red", "Mexican Red"],
    ["A7882C", "Luxor Gold", "Luxor Gold"],
    ["A85307", "Rich Gold", "Rich Gold"],
    ["A86515", "Reno Sand", "Reno Sand"],
    ["A86B6B", "Coral Tree", "Coral Tree"],
    ["A8989B", "Dusty Gray", "Dusty Gray"],
    ["A899E6", "Dull Lavender", "Dull Lavender"],
    ["A8A589", "Tallow", "Tallow"],
    ["A8AE9C", "Bud", "Bud"],
    ["A8AF8E", "Locust", "Locust"],
    ["A8BD9F", "Norway", "Norway"],
    ["A8E3BD", "Chinook", "Chinook"],
    ["A9A491", "Gray Olive", "Gray Olive"],
    ["A9ACB6", "Aluminium", "Aluminium"],
    ["A9B2C3", "Cadet Blue", "Cadet Blue"],
    ["A9B497", "Schist", "Schist"],
    ["A9BDBF", "Tower Gray", "Tower Gray"],
    ["A9BEF2", "Perano", "Perano"],
    ["A9C6C2", "Opal", "Opal"],
    ["AA375A", "Night Shadz", "Night Shadz"],
    ["AA4203", "Fire", "Fire"],
    ["AA8B5B", "Muesli", "Muesli"],
    ["AA8D6F", "Sandal", "Sandal"],
    ["AAA5A9", "Shady Lady", "Shady Lady"],
    ["AAA9CD", "Logan", "Logan"],
    ["AAABB7", "Spun Pearl", "Spun Pearl"],
    ["AAD6E6", "Regent St Blue", "Regent St Blue"],
    ["AAF0D1", "Magic Mint", "Magic Mint"],
    ["AB0563", "Lipstick", "Lipstick"],
    ["AB3472", "Royal Heath", "Royal Heath"],
    ["AB917A", "Sandrift", "Sandrift"],
    ["ABA0D9", "Cold Purple", "Cold Purple"],
    ["ABA196", "Bronco", "Bronco"],
    ["AC8A56", "Limed Oak", "Limed Oak"],
    ["AC91CE", "East Side", "East Side"],
    ["AC9E22", "Lemon Ginger", "Lemon Ginger"],
    ["ACA494", "Napa", "Napa"],
    ["ACA586", "Hillary", "Hillary"],
    ["ACA59F", "Cloudy", "Cloudy"],
    ["ACACAC", "Silver Chalice", "Silver Chalice"],
    ["ACB78E", "Swamp Green", "Swamp Green"],
    ["ACCBB1", "Spring Rain", "Spring Rain"],
    ["ACDD4D", "Conifer", "Conifer"],
    ["ACE1AF", "Celadon", "Celadon"],
    ["AD781B", "Mandalay", "Mandalay"],
    ["ADBED1", "Casper", "Casper"],
    ["ADDFAD", "Moss Green", "Moss Green"],
    ["ADE6C4", "Padua", "Padua"],
    ["ADFF2F", "Green Yellow", "Green Yellow"],
    ["AE4560", "Hippie Pink", "Hippie Pink"],
    ["AE6020", "Desert", "Desert"],
    ["AE809E", "Bouquet", "Bouquet"],
    ["AF4035", "Medium Carmine", "Medium Carmine"],
    ["AF4D43", "Apple Blossom", "Apple Blossom"],
    ["AF593E", "Brown Rust", "Brown Rust"],
    ["AF8751", "Driftwood", "Driftwood"],
    ["AF8F2C", "Alpine", "Alpine"],
    ["AF9F1C", "Lucky", "Lucky"],
    ["AFA09E", "Martini", "Martini"],
    ["AFB1B8", "Bombay", "Bombay"],
    ["AFBDD9", "Pigeon Post", "Pigeon Post"],
    ["B04C6A", "Cadillac", "Cadillac"],
    ["B05D54", "Matrix", "Matrix"],
    ["B05E81", "Tapestry", "Tapestry"],
    ["B06608", "Mai Tai", "Mai Tai"],
    ["B09A95", "Del Rio", "Del Rio"],
    ["B0E0E6", "Powder Blue", "Powder Blue"],
    ["B0E313", "Inch Worm", "Inch Worm"],
    ["B10000", "Bright Red", "Bright Red"],
    ["B14A0B", "Vesuvius", "Vesuvius"],
    ["B1610B", "Pumpkin Skin", "Pumpkin Skin"],
    ["B16D52", "Santa Fe", "Santa Fe"],
    ["B19461", "Teak", "Teak"],
    ["B1E2C1", "Fringy Flower", "Fringy Flower"],
    ["B1F4E7", "Ice Cold", "Ice Cold"],
    ["B20931", "Shiraz", "Shiraz"],
    ["B2A1EA", "Biloba Flower", "Biloba Flower"],
    ["B32D29", "Tall Poppy", "Tall Poppy"],
    ["B35213", "Fiery Orange", "Fiery Orange"],
    ["B38007", "Hot Toddy", "Hot Toddy"],
    ["B3AF95", "Taupe Gray", "Taupe Gray"],
    ["B3C110", "La Rioja", "La Rioja"],
    ["B43332", "Well Read", "Well Read"],
    ["B44668", "Blush", "Blush"],
    ["B4CFD3", "Jungle Mist", "Jungle Mist"],
    ["B57281", "Turkish Rose", "Turkish Rose"],
    ["B57EDC", "Lavender", "Lavender"],
    ["B5A27F", "Mongoose", "Mongoose"],
    ["B5B35C", "Olive Green", "Olive Green"],
    ["B5D2CE", "Jet Stream", "Jet Stream"],
    ["B5ECDF", "Cruise", "Cruise"],
    ["B6316C", "Hibiscus", "Hibiscus"],
    ["B69D98", "Thatch", "Thatch"],
    ["B6B095", "Heathered Gray", "Heathered Gray"],
    ["B6BAA4", "Eagle", "Eagle"],
    ["B6D1EA", "Spindle", "Spindle"],
    ["B6D3BF", "Gum Leaf", "Gum Leaf"],
    ["B7410E", "Rust", "Rust"],
    ["B78E5C", "Muddy Waters", "Muddy Waters"],
    ["B7A214", "Sahara", "Sahara"],
    ["B7A458", "Husk", "Husk"],
    ["B7B1B1", "Nobel", "Nobel"],
    ["B7C3D0", "Heather", "Heather"],
    ["B7F0BE", "Madang", "Madang"],
    ["B81104", "Milano Red", "Milano Red"],
    ["B87333", "Copper", "Copper"],
    ["B8B56A", "Gimblet", "Gimblet"],
    ["B8C1B1", "Green Spring", "Green Spring"],
    ["B8C25D", "Celery", "Celery"],
    ["B8E0F9", "Sail", "Sail"],
    ["B94E48", "Chestnut", "Chestnut"],
    ["B95140", "Crail", "Crail"],
    ["B98D28", "Marigold", "Marigold"],
    ["B9C46A", "Wild Willow", "Wild Willow"],
    ["B9C8AC", "Rainee", "Rainee"],
    ["BA0101", "Guardsman Red", "Guardsman Red"],
    ["BA450C", "Rock Spray", "Rock Spray"],
    ["BA6F1E", "Bourbon", "Bourbon"],
    ["BA7F03", "Pirate Gold", "Pirate Gold"],
    ["BAB1A2", "Nomad", "Nomad"],
    ["BAC7C9", "Submarine", "Submarine"],
    ["BAEEF9", "Charlotte", "Charlotte"],
    ["BB3385", "Medium Red Violet", "Medium Red Violet"],
    ["BB8983", "Brandy Rose", "Brandy Rose"],
    ["BBD009", "Rio Grande", "Rio Grande"],
    ["BBD7C1", "Surf", "Surf"],
    ["BCC9C2", "Powder Ash", "Powder Ash"],
    ["BD5E2E", "Tuscany", "Tuscany"],
    ["BD978E", "Quicksand", "Quicksand"],
    ["BDB1A8", "Silk", "Silk"],
    ["BDB2A1", "Malta", "Malta"],
    ["BDB3C7", "Chatelle", "Chatelle"],
    ["BDBBD7", "Lavender Gray", "Lavender Gray"],
    ["BDBDC6", "French Gray", "French Gray"],
    ["BDC8B3", "Clay Ash", "Clay Ash"],
    ["BDC9CE", "Loblolly", "Loblolly"],
    ["BDEDFD", "French Pass", "French Pass"],
    ["BEA6C3", "London Hue", "London Hue"],
    ["BEB5B7", "Pink Swan", "Pink Swan"],
    ["BEDE0D", "Fuego", "Fuego"],
    ["BF5500", "Rose of Sharon", "Rose of Sharon"],
    ["BFB8B0", "Tide", "Tide"],
    ["BFBED8", "Blue Haze", "Blue Haze"],
    ["BFC1C2", "Silver Sand", "Silver Sand"],
    ["BFC921", "Key Lime Pie", "Key Lime Pie"],
    ["BFDBE2", "Ziggurat", "Ziggurat"],
    ["BFFF00", "Lime", "Lime"],
    ["C02B18", "Thunderbird", "Thunderbird"],
    ["C04737", "Mojo", "Mojo"],
    ["C08081", "Old Rose", "Old Rose"],
    ["C0C0C0", "Silver", "Silver"],
    ["C0D3B9", "Pale Leaf", "Pale Leaf"],
    ["C0D8B6", "Pixie Green", "Pixie Green"],
    ["C1440E", "Tia Maria", "Tia Maria"],
    ["C154C1", "Fuchsia Pink", "Fuchsia Pink"],
    ["C1A004", "Buddha Gold", "Buddha Gold"],
    ["C1B7A4", "Bison Hide", "Bison Hide"],
    ["C1BAB0", "Tea", "Tea"],
    ["C1BECD", "Gray Suit", "Gray Suit"],
    ["C1D7B0", "Sprout", "Sprout"],
    ["C1F07C", "Sulu", "Sulu"],
    ["C26B03", "Indochine", "Indochine"],
    ["C2955D", "Twine", "Twine"],
    ["C2BDB6", "Cotton Seed", "Cotton Seed"],
    ["C2CAC4", "Pumice", "Pumice"],
    ["C2E8E5", "Jagged Ice", "Jagged Ice"],
    ["C32148", "Maroon Flush", "Maroon Flush"],
    ["C3B091", "Indian Khaki", "Indian Khaki"],
    ["C3BFC1", "Pale Slate", "Pale Slate"],
    ["C3C3BD", "Gray Nickel", "Gray Nickel"],
    ["C3CDE6", "Periwinkle Gray", "Periwinkle Gray"],
    ["C3D1D1", "Tiara", "Tiara"],
    ["C3DDF9", "Tropical Blue", "Tropical Blue"],
    ["C41E3A", "Cardinal", "Cardinal"],
    ["C45655", "Fuzzy Wuzzy Brown", "Fuzzy Wuzzy Brown"],
    ["C45719", "Orange Roughy", "Orange Roughy"],
    ["C4C4BC", "Mist Gray", "Mist Gray"],
    ["C4D0B0", "Coriander", "Coriander"],
    ["C4F4EB", "Mint Tulip", "Mint Tulip"],
    ["C54B8C", "Mulberry", "Mulberry"],
    ["C59922", "Nugget", "Nugget"],
    ["C5994B", "Tussock", "Tussock"],
    ["C5DBCA", "Sea Mist", "Sea Mist"],
    ["C5E17A", "Yellow Green", "Yellow Green"],
    ["C62D42", "Brick Red", "Brick Red"],
    ["C6726B", "Contessa", "Contessa"],
    ["C69191", "Oriental Pink", "Oriental Pink"],
    ["C6A84B", "Roti", "Roti"],
    ["C6C3B5", "Ash", "Ash"],
    ["C6C8BD", "Kangaroo", "Kangaroo"],
    ["C6E610", "Las Palmas", "Las Palmas"],
    ["C7031E", "Monza", "Monza"],
    ["C71585", "Red Violet", "Red Violet"],
    ["C7BCA2", "Coral Reef", "Coral Reef"],
    ["C7C1FF", "Melrose", "Melrose"],
    ["C7C4BF", "Cloud", "Cloud"],
    ["C7C9D5", "Ghost", "Ghost"],
    ["C7CD90", "Pine Glade", "Pine Glade"],
    ["C7DDE5", "Botticelli", "Botticelli"],
    ["C88A65", "Antique Brass", "Antique Brass"],
    ["C8A2C8", "Lilac", "Lilac"],
    ["C8A528", "Hokey Pokey", "Hokey Pokey"],
    ["C8AABF", "Lily", "Lily"],
    ["C8B568", "Laser", "Laser"],
    ["C8E3D7", "Edgewater", "Edgewater"],
    ["C96323", "Piper", "Piper"],
    ["C99415", "Pizza", "Pizza"],
    ["C9A0DC", "Light Wisteria", "Light Wisteria"],
    ["C9B29B", "Rodeo Dust", "Rodeo Dust"],
    ["C9B35B", "Sundance", "Sundance"],
    ["C9B93B", "Earls Green", "Earls Green"],
    ["C9C0BB", "Silver Rust", "Silver Rust"],
    ["C9D9D2", "Conch", "Conch"],
    ["C9FFA2", "Reef", "Reef"],
    ["C9FFE5", "Aero Blue", "Aero Blue"],
    ["CA3435", "Flush Mahogany", "Flush Mahogany"],
    ["CABB48", "Turmeric", "Turmeric"],
    ["CADCD4", "Paris White", "Paris White"],
    ["CAE00D", "Bitter Lemon", "Bitter Lemon"],
    ["CAE6DA", "Skeptic", "Skeptic"],
    ["CB8FA9", "Viola", "Viola"],
    ["CBCAB6", "Foggy Gray", "Foggy Gray"],
    ["CBD3B0", "Green Mist", "Green Mist"],
    ["CBDBD6", "Nebula", "Nebula"],
    ["CC3333", "Persian Red", "Persian Red"],
    ["CC5500", "Burnt Orange", "Burnt Orange"],
    ["CC7722", "Ochre", "Ochre"],
    ["CC8899", "Puce", "Puce"],
    ["CCCAA8", "Thistle Green", "Thistle Green"],
    ["CCCCFF", "Periwinkle", "Periwinkle"],
    ["CCFF00", "Electric Lime", "Electric Lime"],
    ["CD5700", "Tenn", "Tenn"],
    ["CD5C5C", "Chestnut Rose", "Chestnut Rose"],
    ["CD8429", "Brandy Punch", "Brandy Punch"],
    ["CDF4FF", "Onahau", "Onahau"],
    ["CEB98F", "Sorrell Brown", "Sorrell Brown"],
    ["CEBABA", "Cold Turkey", "Cold Turkey"],
    ["CEC291", "Yuma", "Yuma"],
    ["CEC7A7", "Chino", "Chino"],
    ["CFA39D", "Eunry", "Eunry"],
    ["CFB53B", "Old Gold", "Old Gold"],
    ["CFDCCF", "Tasman", "Tasman"],
    ["CFE5D2", "Surf Crest", "Surf Crest"],
    ["CFF9F3", "Humming Bird", "Humming Bird"],
    ["CFFAF4", "Scandal", "Scandal"],
    ["D05F04", "Red Stage", "Red Stage"],
    ["D06DA1", "Hopbush", "Hopbush"],
    ["D07D12", "Meteor", "Meteor"],
    ["D0BEF8", "Perfume", "Perfume"],
    ["D0C0E5", "Prelude", "Prelude"],
    ["D0F0C0", "Tea Green", "Tea Green"],
    ["D18F1B", "Geebung", "Geebung"],
    ["D1BEA8", "Vanilla", "Vanilla"],
    ["D1C6B4", "Soft Amber", "Soft Amber"],
    ["D1D2CA", "Celeste", "Celeste"],
    ["D1D2DD", "Mischka", "Mischka"],
    ["D1E231", "Pear", "Pear"],
    ["D2691E", "Hot Cinnamon", "Hot Cinnamon"],
    ["D27D46", "Raw Sienna", "Raw Sienna"],
    ["D29EAA", "Careys Pink", "Careys Pink"],
    ["D2B48C", "Tan", "Tan"],
    ["D2DA97", "Deco", "Deco"],
    ["D2F6DE", "Blue Romance", "Blue Romance"],
    ["D2F8B0", "Gossip", "Gossip"],
    ["D3CBBA", "Sisal", "Sisal"],
    ["D3CDC5", "Swirl", "Swirl"],
    ["D47494", "Charm", "Charm"],
    ["D4B6AF", "Clam Shell", "Clam Shell"],
    ["D4BF8D", "Straw", "Straw"],
    ["D4C4A8", "Akaroa", "Akaroa"],
    ["D4CD16", "Bird Flower", "Bird Flower"],
    ["D4D7D9", "Iron", "Iron"],
    ["D4DFE2", "Geyser", "Geyser"],
    ["D4E2FC", "Hawkes Blue", "Hawkes Blue"],
    ["D54600", "Grenadier", "Grenadier"],
    ["D591A4", "Can Can", "Can Can"],
    ["D59A6F", "Whiskey", "Whiskey"],
    ["D5D195", "Winter Hazel", "Winter Hazel"],
    ["D5F6E3", "Granny Apple", "Granny Apple"],
    ["D69188", "My Pink", "My Pink"],
    ["D6C562", "Tacha", "Tacha"],
    ["D6CEF6", "Moon Raker", "Moon Raker"],
    ["D6D6D1", "Quill Gray", "Quill Gray"],
    ["D6FFDB", "Snowy Mint", "Snowy Mint"],
    ["D7837F", "New York Pink", "New York Pink"],
    ["D7C498", "Pavlova", "Pavlova"],
    ["D7D0FF", "Fog", "Fog"],
    ["D84437", "Valencia", "Valencia"],
    ["D87C63", "Japonica", "Japonica"],
    ["D8BFD8", "Thistle", "Thistle"],
    ["D8C2D5", "Maverick", "Maverick"],
    ["D8FCFA", "Foam", "Foam"],
    ["D94972", "Cabaret", "Cabaret"],
    ["D99376", "Burning Sand", "Burning Sand"],
    ["D9B99B", "Cameo", "Cameo"],
    ["D9D6CF", "Timberwolf", "Timberwolf"],
    ["D9DCC1", "Tana", "Tana"],
    ["D9E4F5", "Link Water", "Link Water"],
    ["D9F7FF", "Mabel", "Mabel"],
    ["DA3287", "Cerise", "Cerise"],
    ["DA5B38", "Flame Pea", "Flame Pea"],
    ["DA6304", "Bamboo", "Bamboo"],
    ["DA6A41", "Red Damask", "Red Damask"],
    ["DA70D6", "Orchid", "Orchid"],
    ["DA8A67", "Copperfield", "Copperfield"],
    ["DAA520", "Golden Grass", "Golden Grass"],
    ["DAECD6", "Zanah", "Zanah"],
    ["DAF4F0", "Iceberg", "Iceberg"],
    ["DAFAFF", "Oyster Bay", "Oyster Bay"],
    ["DB5079", "Cranberry", "Cranberry"],
    ["DB9690", "Petite Orchid", "Petite Orchid"],
    ["DB995E", "Di Serria", "Di Serria"],
    ["DBDBDB", "Alto", "Alto"],
    ["DBFFF8", "Frosted Mint", "Frosted Mint"],
    ["DC143C", "Crimson", "Crimson"],
    ["DC4333", "Punch", "Punch"],
    ["DCB20C", "Galliano", "Galliano"],
    ["DCB4BC", "Blossom", "Blossom"],
    ["DCD747", "Wattle", "Wattle"],
    ["DCD9D2", "Westar", "Westar"],
    ["DCDDCC", "Moon Mist", "Moon Mist"],
    ["DCEDB4", "Caper", "Caper"],
    ["DCF0EA", "Swans Down", "Swans Down"],
    ["DDD6D5", "Swiss Coffee", "Swiss Coffee"],
    ["DDF9F1", "White Ice", "White Ice"],
    ["DE3163", "Cerise Red", "Cerise Red"],
    ["DE6360", "Roman", "Roman"],
    ["DEA681", "Tumbleweed", "Tumbleweed"],
    ["DEBA13", "Gold Tips", "Gold Tips"],
    ["DEC196", "Brandy", "Brandy"],
    ["DECBC6", "Wafer", "Wafer"],
    ["DED4A4", "Sapling", "Sapling"],
    ["DED717", "Barberry", "Barberry"],
    ["DEE5C0", "Beryl Green", "Beryl Green"],
    ["DEF5FF", "Pattens Blue", "Pattens Blue"],
    ["DF73FF", "Heliotrope", "Heliotrope"],
    ["DFBE6F", "Apache", "Apache"],
    ["DFCD6F", "Chenin", "Chenin"],
    ["DFCFDB", "Lola", "Lola"],
    ["DFECDA", "Willow Brook", "Willow Brook"],
    ["DFFF00", "Chartreuse Yellow", "Chartreuse Yellow"],
    ["E0B0FF", "Mauve", "Mauve"],
    ["E0B646", "Anzac", "Anzac"],
    ["E0B974", "Harvest Gold", "Harvest Gold"],
    ["E0C095", "Calico", "Calico"],
    ["E0FFFF", "Baby Blue", "Baby Blue"],
    ["E16865", "Sunglo", "Sunglo"],
    ["E1BC64", "Equator", "Equator"],
    ["E1C0C8", "Pink Flare", "Pink Flare"],
    ["E1E6D6", "Periglacial Blue", "Periglacial Blue"],
    ["E1EAD4", "Kidnapper", "Kidnapper"],
    ["E1F6E8", "Tara", "Tara"],
    ["E25465", "Mandy", "Mandy"],
    ["E2725B", "Terracotta", "Terracotta"],
    ["E28913", "Golden Bell", "Golden Bell"],
    ["E292C0", "Shocking", "Shocking"],
    ["E29418", "Dixie", "Dixie"],
    ["E29CD2", "Light Orchid", "Light Orchid"],
    ["E2D8ED", "Snuff", "Snuff"],
    ["E2EBED", "Mystic", "Mystic"],
    ["E2F3EC", "Apple Green", "Apple Green"],
    ["E30B5C", "Razzmatazz", "Razzmatazz"],
    ["E32636", "Alizarin Crimson", "Alizarin Crimson"],
    ["E34234", "Cinnabar", "Cinnabar"],
    ["E3BEBE", "Cavern Pink", "Cavern Pink"],
    ["E3F5E1", "Peppermint", "Peppermint"],
    ["E3F988", "Mindaro", "Mindaro"],
    ["E47698", "Deep Blush", "Deep Blush"],
    ["E49B0F", "Gamboge", "Gamboge"],
    ["E4C2D5", "Melanie", "Melanie"],
    ["E4CFDE", "Twilight", "Twilight"],
    ["E4D1C0", "Bone", "Bone"],
    ["E4D422", "Sunflower", "Sunflower"],
    ["E4D5B7", "Grain Brown", "Grain Brown"],
    ["E4D69B", "Zombie", "Zombie"],
    ["E4F6E7", "Frostee", "Frostee"],
    ["E4FFD1", "Snow Flurry", "Snow Flurry"],
    ["E52B50", "Amaranth", "Amaranth"],
    ["E5841B", "Zest", "Zest"],
    ["E5CCC9", "Dust Storm", "Dust Storm"],
    ["E5D7BD", "Stark White", "Stark White"],
    ["E5D8AF", "Hampton", "Hampton"],
    ["E5E0E1", "Bon Jour", "Bon Jour"],
    ["E5E5E5", "Mercury", "Mercury"],
    ["E5F9F6", "Polar", "Polar"],
    ["E64E03", "Trinidad", "Trinidad"],
    ["E6BE8A", "Gold Sand", "Gold Sand"],
    ["E6BEA5", "Cashmere", "Cashmere"],
    ["E6D7B9", "Double Spanish White", "Double Spanish White"],
    ["E6E4D4", "Satin Linen", "Satin Linen"],
    ["E6F2EA", "Harp", "Harp"],
    ["E6F8F3", "Off Green", "Off Green"],
    ["E6FFE9", "Hint of Green", "Hint of Green"],
    ["E6FFFF", "Tranquil", "Tranquil"],
    ["E77200", "Mango Tango", "Mango Tango"],
    ["E7730A", "Christine", "Christine"],
    ["E79F8C", "Tonys Pink", "Tonys Pink"],
    ["E79FC4", "Kobi", "Kobi"],
    ["E7BCB4", "Rose Fog", "Rose Fog"],
    ["E7BF05", "Corn", "Corn"],
    ["E7CD8C", "Putty", "Putty"],
    ["E7ECE6", "Gray Nurse", "Gray Nurse"],
    ["E7F8FF", "Lily White", "Lily White"],
    ["E7FEFF", "Bubbles", "Bubbles"],
    ["E89928", "Fire Bush", "Fire Bush"],
    ["E8B9B3", "Shilo", "Shilo"],
    ["E8E0D5", "Pearl Bush", "Pearl Bush"],
    ["E8EBE0", "Green White", "Green White"],
    ["E8F1D4", "Chrome White", "Chrome White"],
    ["E8F2EB", "Gin", "Gin"],
    ["E8F5F2", "Aqua Squeeze", "Aqua Squeeze"],
    ["E96E00", "Clementine", "Clementine"],
    ["E97451", "Burnt Sienna", "Burnt Sienna"],
    ["E97C07", "Tahiti Gold", "Tahiti Gold"],
    ["E9CECD", "Oyster Pink", "Oyster Pink"],
    ["E9D75A", "Confetti", "Confetti"],
    ["E9E3E3", "Ebb", "Ebb"],
    ["E9F8ED", "Ottoman", "Ottoman"],
    ["E9FFFD", "Clear Day", "Clear Day"],
    ["EA88A8", "Carissma", "Carissma"],
    ["EAAE69", "Porsche", "Porsche"],
    ["EAB33B", "Tulip Tree", "Tulip Tree"],
    ["EAC674", "Rob Roy", "Rob Roy"],
    ["EADAB8", "Raffia", "Raffia"],
    ["EAE8D4", "White Rock", "White Rock"],
    ["EAF6EE", "Panache", "Panache"],
    ["EAF6FF", "Solitude", "Solitude"],
    ["EAF9F5", "Aqua Spring", "Aqua Spring"],
    ["EAFFFE", "Dew", "Dew"],
    ["EB9373", "Apricot", "Apricot"],
    ["EBC2AF", "Zinnwaldite", "Zinnwaldite"],
    ["ECA927", "Fuel Yellow", "Fuel Yellow"],
    ["ECC54E", "Ronchi", "Ronchi"],
    ["ECC7EE", "French Lilac", "French Lilac"],
    ["ECCDB9", "Just Right", "Just Right"],
    ["ECE090", "Wild Rice", "Wild Rice"],
    ["ECEBBD", "Fall Green", "Fall Green"],
    ["ECEBCE", "Aths Special", "Aths Special"],
    ["ECF245", "Starship", "Starship"],
    ["ED0A3F", "Red Ribbon", "Red Ribbon"],
    ["ED7A1C", "Tango", "Tango"],
    ["ED9121", "Carrot Orange", "Carrot Orange"],
    ["ED989E", "Sea Pink", "Sea Pink"],
    ["EDB381", "Tacao", "Tacao"],
    ["EDC9AF", "Desert Sand", "Desert Sand"],
    ["EDCDAB", "Pancho", "Pancho"],
    ["EDDCB1", "Chamois", "Chamois"],
    ["EDEA99", "Primrose", "Primrose"],
    ["EDF5DD", "Frost", "Frost"],
    ["EDF5F5", "Aqua Haze", "Aqua Haze"],
    ["EDF6FF", "Zumthor", "Zumthor"],
    ["EDF9F1", "Narvik", "Narvik"],
    ["EDFC84", "Honeysuckle", "Honeysuckle"],
    ["EE82EE", "Lavender Magenta", "Lavender Magenta"],
    ["EEC1BE", "Beauty Bush", "Beauty Bush"],
    ["EED794", "Chalky", "Chalky"],
    ["EED9C4", "Almond", "Almond"],
    ["EEDC82", "Flax", "Flax"],
    ["EEDEDA", "Bizarre", "Bizarre"],
    ["EEE3AD", "Double Colonial White", "Double Colonial White"],
    ["EEEEE8", "Cararra", "Cararra"],
    ["EEEF78", "Manz", "Manz"],
    ["EEF0C8", "Tahuna Sands", "Tahuna Sands"],
    ["EEF0F3", "Athens Gray", "Athens Gray"],
    ["EEF3C3", "Tusk", "Tusk"],
    ["EEF4DE", "Loafer", "Loafer"],
    ["EEF6F7", "Catskill White", "Catskill White"],
    ["EEFDFF", "Twilight Blue", "Twilight Blue"],
    ["EEFF9A", "Jonquil", "Jonquil"],
    ["EEFFE2", "Rice Flower", "Rice Flower"],
    ["EF863F", "Jaffa", "Jaffa"],
    ["EFEFEF", "Gallery", "Gallery"],
    ["EFF2F3", "Porcelain", "Porcelain"],
    ["F091A9", "Mauvelous", "Mauvelous"],
    ["F0D52D", "Golden Dream", "Golden Dream"],
    ["F0DB7D", "Golden Sand", "Golden Sand"],
    ["F0DC82", "Buff", "Buff"],
    ["F0E2EC", "Prim", "Prim"],
    ["F0E68C", "Khaki", "Khaki"],
    ["F0EEFD", "Selago", "Selago"],
    ["F0EEFF", "Titan White", "Titan White"],
    ["F0F8FF", "Alice Blue", "Alice Blue"],
    ["F0FCEA", "Feta", "Feta"],
    ["F18200", "Gold Drop", "Gold Drop"],
    ["F19BAB", "Wewak", "Wewak"],
    ["F1E788", "Sahara Sand", "Sahara Sand"],
    ["F1E9D2", "Parchment", "Parchment"],
    ["F1E9FF", "Blue Chalk", "Blue Chalk"],
    ["F1EEC1", "Mint Julep", "Mint Julep"],
    ["F1F1F1", "Seashell", "Seashell"],
    ["F1F7F2", "Saltpan", "Saltpan"],
    ["F1FFAD", "Tidal", "Tidal"],
    ["F1FFC8", "Chiffon", "Chiffon"],
    ["F2552A", "Flamingo", "Flamingo"],
    ["F28500", "Tangerine", "Tangerine"],
    ["F2C3B2", "Mandys Pink", "Mandys Pink"],
    ["F2F2F2", "Concrete", "Concrete"],
    ["F2FAFA", "Black Squeeze", "Black Squeeze"],
    ["F34723", "Pomegranate", "Pomegranate"],
    ["F3AD16", "Buttercup", "Buttercup"],
    ["F3D69D", "New Orleans", "New Orleans"],
    ["F3D9DF", "Vanilla Ice", "Vanilla Ice"],
    ["F3E7BB", "Sidecar", "Sidecar"],
    ["F3E9E5", "Dawn Pink", "Dawn Pink"],
    ["F3EDCF", "Wheatfield", "Wheatfield"],
    ["F3FB62", "Canary", "Canary"],
    ["F3FBD4", "Orinoco", "Orinoco"],
    ["F3FFD8", "Carla", "Carla"],
    ["F400A1", "Hollywood Cerise", "Hollywood Cerise"],
    ["F4A460", "Sandy brown", "Sandy brown"],
    ["F4C430", "Saffron", "Saffron"],
    ["F4D81C", "Ripe Lemon", "Ripe Lemon"],
    ["F4EBD3", "Janna", "Janna"],
    ["F4F2EE", "Pampas", "Pampas"],
    ["F4F4F4", "Wild Sand", "Wild Sand"],
    ["F4F8FF", "Zircon", "Zircon"],
    ["F57584", "Froly", "Froly"],
    ["F5C85C", "Cream Can", "Cream Can"],
    ["F5C999", "Manhattan", "Manhattan"],
    ["F5D5A0", "Maize", "Maize"],
    ["F5DEB3", "Wheat", "Wheat"],
    ["F5E7A2", "Sandwisp", "Sandwisp"],
    ["F5E7E2", "Pot Pourri", "Pot Pourri"],
    ["F5E9D3", "Albescent White", "Albescent White"],
    ["F5EDEF", "Soft Peach", "Soft Peach"],
    ["F5F3E5", "Ecru White", "Ecru White"],
    ["F5F5DC", "Beige", "Beige"],
    ["F5FB3D", "Golden Fizz", "Golden Fizz"],
    ["F5FFBE", "Australian Mint", "Australian Mint"],
    ["F64A8A", "French Rose", "French Rose"],
    ["F653A6", "Brilliant Rose", "Brilliant Rose"],
    ["F6A4C9", "Illusion", "Illusion"],
    ["F6F0E6", "Merino", "Merino"],
    ["F6F7F7", "Black Haze", "Black Haze"],
    ["F6FFDC", "Spring Sun", "Spring Sun"],
    ["F7468A", "Violet Red", "Violet Red"],
    ["F77703", "Chilean Fire", "Chilean Fire"],
    ["F77FBE", "Persian Pink", "Persian Pink"],
    ["F7B668", "Rajah", "Rajah"],
    ["F7C8DA", "Azalea", "Azalea"],
    ["F7DBE6", "We Peep", "We Peep"],
    ["F7F2E1", "Quarter Spanish White", "Quarter Spanish White"],
    ["F7F5FA", "Whisper", "Whisper"],
    ["F7FAF7", "Snow Drift", "Snow Drift"],
    ["F8B853", "Casablanca", "Casablanca"],
    ["F8C3DF", "Chantilly", "Chantilly"],
    ["F8D9E9", "Cherub", "Cherub"],
    ["F8DB9D", "Marzipan", "Marzipan"],
    ["F8DD5C", "Energy Yellow", "Energy Yellow"],
    ["F8E4BF", "Givry", "Givry"],
    ["F8F0E8", "White Linen", "White Linen"],
    ["F8F4FF", "Magnolia", "Magnolia"],
    ["F8F6F1", "Spring Wood", "Spring Wood"],
    ["F8F7DC", "Coconut Cream", "Coconut Cream"],
    ["F8F7FC", "White Lilac", "White Lilac"],
    ["F8F8F7", "Desert Storm", "Desert Storm"],
    ["F8F99C", "Texas", "Texas"],
    ["F8FACD", "Corn Field", "Corn Field"],
    ["F8FDD3", "Mimosa", "Mimosa"],
    ["F95A61", "Carnation", "Carnation"],
    ["F9BF58", "Saffron Mango", "Saffron Mango"],
    ["F9E0ED", "Carousel Pink", "Carousel Pink"],
    ["F9E4BC", "Dairy Cream", "Dairy Cream"],
    ["F9E663", "Portica", "Portica"],
    ["F9EAF3", "Amour", "Amour"],
    ["F9F8E4", "Rum Swizzle", "Rum Swizzle"],
    ["F9FF8B", "Dolly", "Dolly"],
    ["F9FFF6", "Sugar Cane", "Sugar Cane"],
    ["FA7814", "Ecstasy", "Ecstasy"],
    ["FA9D5A", "Tan Hide", "Tan Hide"],
    ["FAD3A2", "Corvette", "Corvette"],
    ["FADFAD", "Peach Yellow", "Peach Yellow"],
    ["FAE600", "Turbo", "Turbo"],
    ["FAEAB9", "Astra", "Astra"],
    ["FAECCC", "Champagne", "Champagne"],
    ["FAF0E6", "Linen", "Linen"],
    ["FAF3F0", "Fantasy", "Fantasy"],
    ["FAF7D6", "Citrine White", "Citrine White"],
    ["FAFAFA", "Alabaster", "Alabaster"],
    ["FAFDE4", "Hint of Yellow", "Hint of Yellow"],
    ["FAFFA4", "Milan", "Milan"],
    ["FB607F", "Brink Pink", "Brink Pink"],
    ["FB8989", "Geraldine", "Geraldine"],
    ["FBA0E3", "Lavender Rose", "Lavender Rose"],
    ["FBA129", "Sea Buckthorn", "Sea Buckthorn"],
    ["FBAC13", "Sun", "Sun"],
    ["FBAED2", "Lavender Pink", "Lavender Pink"],
    ["FBB2A3", "Rose Bud", "Rose Bud"],
    ["FBBEDA", "Cupid", "Cupid"],
    ["FBCCE7", "Classic Rose", "Classic Rose"],
    ["FBCEB1", "Apricot Peach", "Apricot Peach"],
    ["FBE7B2", "Banana Mania", "Banana Mania"],
    ["FBE870", "Marigold Yellow", "Marigold Yellow"],
    ["FBE96C", "Festival", "Festival"],
    ["FBEA8C", "Sweet Corn", "Sweet Corn"],
    ["FBEC5D", "Candy Corn", "Candy Corn"],
    ["FBF9F9", "Hint of Red", "Hint of Red"],
    ["FBFFBA", "Shalimar", "Shalimar"],
    ["FC0FC0", "Shocking Pink", "Shocking Pink"],
    ["FC80A5", "Tickle Me Pink", "Tickle Me Pink"],
    ["FC9C1D", "Tree Poppy", "Tree Poppy"],
    ["FCC01E", "Lightning Yellow", "Lightning Yellow"],
    ["FCD667", "Goldenrod", "Goldenrod"],
    ["FCD917", "Candlelight", "Candlelight"],
    ["FCDA98", "Cherokee", "Cherokee"],
    ["FCF4D0", "Double Pearl Lusta", "Double Pearl Lusta"],
    ["FCF4DC", "Pearl Lusta", "Pearl Lusta"],
    ["FCF8F7", "Vista White", "Vista White"],
    ["FCFBF3", "Bianca", "Bianca"],
    ["FCFEDA", "Moon Glow", "Moon Glow"],
    ["FCFFE7", "China Ivory", "China Ivory"],
    ["FCFFF9", "Ceramic", "Ceramic"],
    ["FD0E35", "Torch Red", "Torch Red"],
    ["FD5B78", "Wild Watermelon", "Wild Watermelon"],
    ["FD7B33", "Crusta", "Crusta"],
    ["FD7C07", "Sorbus", "Sorbus"],
    ["FD9FA2", "Sweet Pink", "Sweet Pink"],
    ["FDD5B1", "Light Apricot", "Light Apricot"],
    ["FDD7E4", "Pig Pink", "Pig Pink"],
    ["FDE1DC", "Cinderella", "Cinderella"],
    ["FDE295", "Golden Glow", "Golden Glow"],
    ["FDE910", "Lemon", "Lemon"],
    ["FDF5E6", "Old Lace", "Old Lace"],
    ["FDF6D3", "Half Colonial White", "Half Colonial White"],
    ["FDF7AD", "Drover", "Drover"],
    ["FDFEB8", "Pale Prim", "Pale Prim"],
    ["FDFFD5", "Cumulus", "Cumulus"],
    ["FE28A2", "Persian Rose", "Persian Rose"],
    ["FE4C40", "Sunset Orange", "Sunset Orange"],
    ["FE6F5E", "Bittersweet", "Bittersweet"],
    ["FE9D04", "California", "California"],
    ["FEA904", "Yellow Sea", "Yellow Sea"],
    ["FEBAAD", "Melon", "Melon"],
    ["FED33C", "Bright Sun", "Bright Sun"],
    ["FED85D", "Dandelion", "Dandelion"],
    ["FEDB8D", "Salomie", "Salomie"],
    ["FEE5AC", "Cape Honey", "Cape Honey"],
    ["FEEBF3", "Remy", "Remy"],
    ["FEEFCE", "Oasis", "Oasis"],
    ["FEF0EC", "Bridesmaid", "Bridesmaid"],
    ["FEF2C7", "Beeswax", "Beeswax"],
    ["FEF3D8", "Bleach White", "Bleach White"],
    ["FEF4CC", "Pipi", "Pipi"],
    ["FEF4DB", "Half Spanish White", "Half Spanish White"],
    ["FEF4F8", "Wisp Pink", "Wisp Pink"],
    ["FEF5F1", "Provincial Pink", "Provincial Pink"],
    ["FEF7DE", "Half Dutch White", "Half Dutch White"],
    ["FEF8E2", "Solitaire", "Solitaire"],
    ["FEF8FF", "White Pointer", "White Pointer"],
    ["FEF9E3", "Off Yellow", "Off Yellow"],
    ["FEFCED", "Orange White", "Orange White"],
    ["FF0000", "Red", "Red"],
    ["FF007F", "Rose", "Rose"],
    ["FF00CC", "Purple Pizzazz", "Purple Pizzazz"],
    ["FF00FF", "Magenta / Fuchsia", "Magenta / Fuchsia"],
    ["FF2400", "Scarlet", "Scarlet"],
    ["FF3399", "Wild Strawberry", "Wild Strawberry"],
    ["FF33CC", "Razzle Dazzle Rose", "Razzle Dazzle Rose"],
    ["FF355E", "Radical Red", "Radical Red"],
    ["FF3F34", "Red Orange", "Red Orange"],
    ["FF4040", "Coral Red", "Coral Red"],
    ["FF4D00", "Vermilion", "Vermilion"],
    ["FF4F00", "International Orange", "International Orange"],
    ["FF6037", "Outrageous Orange", "Outrageous Orange"],
    ["FF6600", "Blaze Orange", "Blaze Orange"],
    ["FF66FF", "Pink Flamingo", "Pink Flamingo"],
    ["FF681F", "Orange", "Orange"],
    ["FF69B4", "Hot Pink", "Hot Pink"],
    ["FF6B53", "Persimmon", "Persimmon"],
    ["FF6FFF", "Blush Pink", "Blush Pink"],
    ["FF7034", "Burning Orange", "Burning Orange"],
    ["FF7518", "Pumpkin", "Pumpkin"],
    ["FF7D07", "Flamenco", "Flamenco"],
    ["FF7F00", "Flush Orange", "Flush Orange"],
    ["FF7F50", "Coral", "Coral"],
    ["FF8C69", "Salmon", "Salmon"],
    ["FF9000", "Pizazz", "Pizazz"],
    ["FF910F", "West Side", "West Side"],
    ["FF91A4", "Pink Salmon", "Pink Salmon"],
    ["FF9933", "Neon Carrot", "Neon Carrot"],
    ["FF9966", "Atomic Tangerine", "Atomic Tangerine"],
    ["FF9980", "Vivid Tangerine", "Vivid Tangerine"],
    ["FF9E2C", "Sunshade", "Sunshade"],
    ["FFA000", "Orange Peel", "Orange Peel"],
    ["FFA194", "Mona Lisa", "Mona Lisa"],
    ["FFA500", "Web Orange", "Web Orange"],
    ["FFA6C9", "Carnation Pink", "Carnation Pink"],
    ["FFAB81", "Hit Pink", "Hit Pink"],
    ["FFAE42", "Yellow Orange", "Yellow Orange"],
    ["FFB0AC", "Cornflower Lilac", "Cornflower Lilac"],
    ["FFB1B3", "Sundown", "Sundown"],
    ["FFB31F", "My Sin", "My Sin"],
    ["FFB555", "Texas Rose", "Texas Rose"],
    ["FFB7D5", "Cotton Candy", "Cotton Candy"],
    ["FFB97B", "Macaroni and Cheese", "Macaroni and Cheese"],
    ["FFBA00", "Selective Yellow", "Selective Yellow"],
    ["FFBD5F", "Koromiko", "Koromiko"],
    ["FFBF00", "Amber", "Amber"],
    ["FFC0A8", "Wax Flower", "Wax Flower"],
    ["FFC0CB", "Pink", "Pink"],
    ["FFC3C0", "Your Pink", "Your Pink"],
    ["FFC901", "Supernova", "Supernova"],
    ["FFCBA4", "Flesh", "Flesh"],
    ["FFCC33", "Sunglow", "Sunglow"],
    ["FFCC5C", "Golden Tainoi", "Golden Tainoi"],
    ["FFCC99", "Peach Orange", "Peach Orange"],
    ["FFCD8C", "Chardonnay", "Chardonnay"],
    ["FFD1DC", "Pastel Pink", "Pastel Pink"],
    ["FFD2B7", "Romantic", "Romantic"],
    ["FFD38C", "Grandis", "Grandis"],
    ["FFD700", "Gold", "Gold"],
    ["FFD800", "School bus Yellow", "School bus Yellow"],
    ["FFD8D9", "Cosmos", "Cosmos"],
    ["FFDB58", "Mustard", "Mustard"],
    ["FFDCD6", "Peach Schnapps", "Peach Schnapps"],
    ["FFDDAF", "Caramel", "Caramel"],
    ["FFDDCD", "Tuft Bush", "Tuft Bush"],
    ["FFDDCF", "Watusi", "Watusi"],
    ["FFDDF4", "Pink Lace", "Pink Lace"],
    ["FFDEAD", "Navajo White", "Navajo White"],
    ["FFDEB3", "Frangipani", "Frangipani"],
    ["FFE1DF", "Pippin", "Pippin"],
    ["FFE1F2", "Pale Rose", "Pale Rose"],
    ["FFE2C5", "Negroni", "Negroni"],
    ["FFE5A0", "Cream Brulee", "Cream Brulee"],
    ["FFE5B4", "Peach", "Peach"],
    ["FFE6C7", "Tequila", "Tequila"],
    ["FFE772", "Kournikova", "Kournikova"],
    ["FFEAC8", "Sandy Beach", "Sandy Beach"],
    ["FFEAD4", "Karry", "Karry"],
    ["FFEC13", "Broom", "Broom"],
    ["FFEDBC", "Colonial White", "Colonial White"],
    ["FFEED8", "Derby", "Derby"],
    ["FFEFA1", "Vis Vis", "Vis Vis"],
    ["FFEFC1", "Egg White", "Egg White"],
    ["FFEFD5", "Papaya Whip", "Papaya Whip"],
    ["FFEFEC", "Fair Pink", "Fair Pink"],
    ["FFF0DB", "Peach Cream", "Peach Cream"],
    ["FFF0F5", "Lavender blush", "Lavender blush"],
    ["FFF14F", "Gorse", "Gorse"],
    ["FFF1B5", "Buttermilk", "Buttermilk"],
    ["FFF1D8", "Pink Lady", "Pink Lady"],
    ["FFF1EE", "Forget Me Not", "Forget Me Not"],
    ["FFF1F9", "Tutu", "Tutu"],
    ["FFF39D", "Picasso", "Picasso"],
    ["FFF3F1", "Chardon", "Chardon"],
    ["FFF46E", "Paris Daisy", "Paris Daisy"],
    ["FFF4CE", "Barley White", "Barley White"],
    ["FFF4DD", "Egg Sour", "Egg Sour"],
    ["FFF4E0", "Sazerac", "Sazerac"],
    ["FFF4E8", "Serenade", "Serenade"],
    ["FFF4F3", "Chablis", "Chablis"],
    ["FFF5EE", "Seashell Peach", "Seashell Peach"],
    ["FFF5F3", "Sauvignon", "Sauvignon"],
    ["FFF6D4", "Milk Punch", "Milk Punch"],
    ["FFF6DF", "Varden", "Varden"],
    ["FFF6F5", "Rose White", "Rose White"],
    ["FFF8D1", "Baja White", "Baja White"],
    ["FFF9E2", "Gin Fizz", "Gin Fizz"],
    ["FFF9E6", "Early Dawn", "Early Dawn"],
    ["FFFACD", "Lemon Chiffon", "Lemon Chiffon"],
    ["FFFAF4", "Bridal Heath", "Bridal Heath"],
    ["FFFBDC", "Scotch Mist", "Scotch Mist"],
    ["FFFBF9", "Soapstone", "Soapstone"],
    ["FFFC99", "Witch Haze", "Witch Haze"],
    ["FFFCEA", "Buttery White", "Buttery White"],
    ["FFFCEE", "Island Spice", "Island Spice"],
    ["FFFDD0", "Cream", "Cream"],
    ["FFFDE6", "Chilean Heath", "Chilean Heath"],
    ["FFFDE8", "Travertine", "Travertine"],
    ["FFFDF3", "Orchid White", "Orchid White"],
    ["FFFDF4", "Quarter Pearl Lusta", "Quarter Pearl Lusta"],
    ["FFFEE1", "Half and Half", "Half and Half"],
    ["FFFEEC", "Apricot White", "Apricot White"],
    ["FFFEF0", "Rice Cake", "Rice Cake"],
    ["FFFEF6", "Black White", "Black White"],
    ["FFFEFD", "Romance", "Romance"],
    ["FFFF00", "Yellow", "Yellow"],
    ["FFFF66", "Laser Lemon", "Laser Lemon"],
    ["FFFF99", "Pale Canary", "Pale Canary"],
    ["FFFFB4", "Portafino", "Portafino"],
    ["FFFFF0", "Ivory", "Ivory"],
    ["FFFFFF", "White", "White"],
  ],
};

ntc.init();

module.exports = ntc;
